apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-03-19T14:04:31Z"
  labels:
    run: crpod
  name: crpod
  namespace: default
  resourceVersion: "36312"
  uid: e111d6b8-66b6-49cf-b371-0ee7cfeba793
spec:
  clusterIP: 10.211.9.251
  clusterIPs:
  - 10.211.9.251
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32590
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: crpod
  sessionAffinity: None
  type: NodePort
