apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: mysql-deploy
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-03-19T11:24:18Z"
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: mysql-deploy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: 8.0.36
    helm.sh/chart: mysql-10.1.0
  name: mysql-deploy
  namespace: default
  resourceVersion: "18171"
  uid: 0c166ce9-8bc7-4c88-b3df-bd4a4d54de4a
spec:
  clusterIP: 10.211.75.105
  clusterIPs:
  - 10.211.75.105
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mysql
    nodePort: 31917
    port: 3306
    protocol: TCP
    targetPort: mysql
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: mysql-deploy
    app.kubernetes.io/name: mysql
  sessionAffinity: None
  type: NodePort
